# Generated by Django 3.1.1 on 2020-10-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_for_user',
            name='override_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Разрешено ли перерешать тест'),
        ),
    ]
