# Generated by Django 3.1.1 on 2020-10-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipe', '0002_test_for_user_override_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='decision_time',
            field=models.TimeField(blank=True, default=None, verbose_name='Время на решение теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='voprosi_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Число вопросов'),
        ),
    ]
