# Generated by Django 3.1.1 on 2020-10-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototipe', '0003_auto_20201003_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='decision_time',
            field=models.TimeField(blank=True, default='01:00:00', verbose_name='Время на решение теста'),
        ),
    ]
